/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuyTicketsRouteImport } from './routes/buy-tickets'
import { Route as IndexRouteImport } from './routes/index'

const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTicketsRoute = BuyTicketsRouteImport.update({
  id: '/buy-tickets',
  path: '/buy-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy-tickets': typeof BuyTicketsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/details': typeof DetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy-tickets': typeof BuyTicketsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/details': typeof DetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy-tickets': typeof BuyTicketsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/details': typeof DetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buy-tickets' | '/contact' | '/dashboard' | '/details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buy-tickets' | '/contact' | '/dashboard' | '/details'
  id: '__root__' | '/' | '/buy-tickets' | '/contact' | '/dashboard' | '/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyTicketsRoute: typeof BuyTicketsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DetailsRoute: typeof DetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-tickets': {
      id: '/buy-tickets'
      path: '/buy-tickets'
      fullPath: '/buy-tickets'
      preLoaderRoute: typeof BuyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyTicketsRoute: BuyTicketsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DetailsRoute: DetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
